import type { Submission, Project, Ward, DashboardStats, Theme } from "@/types";

export const MOCK_WARDS: Ward[] = [
  { id: "ward-01", name: "Ward 1 — Central",  population: 18500, submission_count: 21, top_theme: "roads"       },
  { id: "ward-02", name: "Ward 2 — North",    population: 22000, submission_count: 18, top_theme: "health"      },
  { id: "ward-03", name: "Ward 3 — East",     population: 31000, submission_count: 47, top_theme: "schools"     },
  { id: "ward-04", name: "Ward 4 — South",    population: 19200, submission_count: 29, top_theme: "electricity" },
  { id: "ward-05", name: "Ward 5 — West",     population: 24800, submission_count: 33, top_theme: "water"       },
];

export const MOCK_THEMES: Theme[] = [
  { id: "t-1", key: "schools",     name: "Schools & Education",  submission_count: 47 },
  { id: "t-2", key: "roads",       name: "Roads & Transport",    submission_count: 38 },
  { id: "t-3", key: "water",       name: "Water & Sanitation",   submission_count: 33 },
  { id: "t-4", key: "health",      name: "Healthcare",           submission_count: 28 },
  { id: "t-5", key: "electricity", name: "Electricity",          submission_count: 21 },
  { id: "t-6", key: "other",       name: "Other",                submission_count: 9  },
];

export const MOCK_SUBMISSIONS: Submission[] = [
  {
    id: "sub-001",
    channel: "web",
    text_raw: "The road to our village has been broken for 2 years. Every monsoon it gets worse. Children cannot go to school safely.",
    text_translated: "The road to our village has been broken for 2 years.",
    lang: "en",
    lat: 28.6139, lng: 77.2090,
    ward_id: "ward-03", ward_name: "Ward 3 — East",
    themes: ["roads", "schools"],
    urgency_score: 0.82, urgency_level: "high",
    created_at: "2024-06-10T09:12:00Z",
  },
  {
    id: "sub-002",
    channel: "whatsapp",
    text_raw: "हमारे वार्ड में कोई सरकारी स्कूल नहीं है। बच्चों को 7 किलोमीटर दूर जाना पड़ता है।",
    text_translated: "There is no government school in our ward. Children have to go 7 kilometres away.",
    lang: "hi",
    lat: 28.6200, lng: 77.2150,
    ward_id: "ward-03", ward_name: "Ward 3 — East",
    themes: ["schools"],
    urgency_score: 0.95, urgency_level: "critical",
    created_at: "2024-06-10T10:45:00Z",
  },
  {
    id: "sub-003",
    channel: "web",
    text_raw: "Water supply is very irregular. We get water only twice a week for 30 minutes.",
    text_translated: "Water supply is very irregular. We get water only twice a week for 30 minutes.",
    lang: "en",
    lat: 28.6300, lng: 77.2200,
    ward_id: "ward-05", ward_name: "Ward 5 — West",
    themes: ["water"],
    urgency_score: 0.78, urgency_level: "high",
    created_at: "2024-06-11T07:30:00Z",
  },
  {
    id: "sub-004",
    channel: "voice",
    text_raw: "The primary health centre in ward 2 has been closed for 6 months. Pregnant women have to travel 20km.",
    text_translated: "The primary health centre in ward 2 has been closed for 6 months.",
    lang: "en",
    lat: 28.6050, lng: 77.1980,
    ward_id: "ward-02", ward_name: "Ward 2 — North",
    themes: ["health"],
    urgency_score: 0.98, urgency_level: "critical",
    created_at: "2024-06-11T14:00:00Z",
  },
  {
    id: "sub-005",
    channel: "web",
    text_raw: "Power cuts for 8–10 hours daily. Small businesses are suffering. Need reliable electricity.",
    text_translated: "Power cuts for 8–10 hours daily. Small businesses are suffering.",
    lang: "en",
    lat: 28.6180, lng: 77.2050,
    ward_id: "ward-04", ward_name: "Ward 4 — South",
    themes: ["electricity"],
    urgency_score: 0.75, urgency_level: "high",
    created_at: "2024-06-12T11:20:00Z",
  },
  {
    id: "sub-006",
    channel: "web",
    text_raw: "The school building is in very poor condition. Roof leaks during monsoon. 400 students are affected.",
    text_translated: "The school building is in very poor condition. Roof leaks during monsoon.",
    lang: "en",
    lat: 28.6210, lng: 77.2180,
    ward_id: "ward-03", ward_name: "Ward 3 — East",
    themes: ["schools"],
    urgency_score: 0.88, urgency_level: "critical",
    created_at: "2024-06-12T16:45:00Z",
  },
  {
    id: "sub-007",
    channel: "web",
    text_raw: "નમસ્તે ભારત — અહીં 3 દિવસથી વીજળી નથી. ખૂબ જ તાત્કાલિક છે.",
    text_translated: "Hello India — there has been no electricity for 3 days here. It is very urgent.",
    lang: "gu",
    lat: 28.6080, lng: 77.2010,
    ward_id: "ward-03", ward_name: "Ward 3 — East",
    themes: ["electricity"],
    urgency_score: 0.88, urgency_level: "high",
    created_at: "2024-07-01T09:00:00Z",
  },
  {
    id: "sub-008",
    channel: "web",
    text_raw: "नमस्ते इंडिया — हमारी सड़कें बहुत खराब हैं। कृपया मरम्मत करवाएं।",
    text_translated: "Hello India — our roads are in very bad condition. Please get them repaired.",
    lang: "hi",
    lat: 28.6100, lng: 77.2060,
    ward_id: "ward-02", ward_name: "Ward 2 — North",
    themes: ["roads"],
    urgency_score: 0.72, urgency_level: "medium",
    created_at: "2024-07-02T08:30:00Z",
  },
  {
    id: "sub-009",
    channel: "web",
    text_raw: "ஒரு வாரமாக தண்ணீர் வரவில்லை. மக்கள் மிகவும் கஷ்டப்படுகிறார்கள்.",
    text_translated: "There has been no water supply for a week. People are suffering a lot.",
    lang: "ta",
    lat: 28.6250, lng: 77.2120,
    ward_id: "ward-05", ward_name: "Ward 5 — West",
    themes: ["water"],
    urgency_score: 0.91, urgency_level: "critical",
    created_at: "2024-07-01T14:00:00Z",
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-001",
    title: "New Primary School — Ward 3 East",
    description: "Construction of a new government primary school to serve the 5,800 school-age children in Ward 3. Current nearest school is 6.2 km away.",
    theme: "schools",
    ward_id: "ward-03", ward_name: "Ward 3 — East",
    demand_score: 0.95,
    gap_score: 0.92,
    feasibility_score: 0.70,
    urgency_score: 0.91,
    priority_score: 0.89,
    priority_rank: 1,
    evidence_text: "47 submissions in Ward 3 cite school access as critical. Ward has 5,800 school-age children but the nearest school is 6.2 km away — well above the 2 km safe-walk threshold. The local development plan includes a reserved plot in sector 7B.",
    submission_count: 47,
    affected_population: 5800,
    source: "combined",
  },
  {
    id: "proj-002",
    title: "Primary Health Centre Restoration — Ward 2",
    description: "Reopen and upgrade the Ward 2 PHC that has been non-operational for 6 months. Affects 22,000 residents including high-risk pregnant women.",
    theme: "health",
    ward_id: "ward-02", ward_name: "Ward 2 — North",
    demand_score: 0.85,
    gap_score: 0.97,
    feasibility_score: 0.90,
    urgency_score: 0.98,
    priority_score: 0.92,
    priority_rank: 2,
    evidence_text: "18 submissions from Ward 2 specifically mention the closed health centre. Infrastructure gap score is 0.97 — residents must travel 20 km for basic care. Restoration requires staffing and equipment procurement only; building is intact.",
    submission_count: 18,
    affected_population: 22000,
    source: "combined",
  },
  {
    id: "proj-003",
    title: "Water Pipeline Extension — Ward 5 West",
    description: "Extend water supply pipeline to underserved areas of Ward 5 where supply is limited to twice weekly.",
    theme: "water",
    ward_id: "ward-05", ward_name: "Ward 5 — West",
    demand_score: 0.80,
    gap_score: 0.78,
    feasibility_score: 0.75,
    urgency_score: 0.78,
    priority_score: 0.78,
    priority_rank: 3,
    evidence_text: "33 water-related submissions from Ward 5. Residents receive water only 2x per week. Municipal data confirms pipeline coverage gap of ~40% in the ward's eastern sector.",
    submission_count: 33,
    affected_population: 12400,
    source: "citizen",
  },
  {
    id: "proj-004",
    title: "Road Resurfacing — Ward 3 Village Connector",
    description: "Resurface the 4.2 km connector road linking 3 villages to the main highway, damaged beyond repair after consecutive monsoons.",
    theme: "roads",
    ward_id: "ward-03", ward_name: "Ward 3 — East",
    demand_score: 0.72,
    gap_score: 0.65,
    feasibility_score: 0.80,
    urgency_score: 0.82,
    priority_score: 0.72,
    priority_rank: 4,
    evidence_text: "38 road-related submissions, concentrated on the village connector. Road damage forces a 12 km detour. District roads department has confirmed it is beyond patch repair.",
    submission_count: 38,
    affected_population: 8200,
    source: "combined",
  },
  {
    id: "proj-005",
    title: "Electricity Substation Upgrade — Ward 4 South",
    description: "Upgrade the overloaded Ward 4 distribution substation to eliminate 8–10 hour daily power cuts affecting residents and small businesses.",
    theme: "electricity",
    ward_id: "ward-04", ward_name: "Ward 4 — South",
    demand_score: 0.68,
    gap_score: 0.72,
    feasibility_score: 0.65,
    urgency_score: 0.75,
    priority_score: 0.70,
    priority_rank: 5,
    evidence_text: "29 electricity submissions from Ward 4. Power utility audit confirms the substation is running at 140% capacity. Upgrade cost estimated at ₹1.2 Cr.",
    submission_count: 29,
    affected_population: 19200,
    source: "citizen",
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  total_submissions: 176,
  submissions_today: 12,
  top_themes: [
    { theme: "schools",     count: 47 },
    { theme: "roads",       count: 38 },
    { theme: "water",       count: 33 },
    { theme: "health",      count: 28 },
    { theme: "electricity", count: 21 },
    { theme: "other",       count: 9  },
  ],
  wards_covered: 5,
  top_projects: MOCK_PROJECTS,
};

// Simulated API delay
export const delay = (ms: number) => new Promise((r) => setTimeout(r, ms));
